### ISSUE TITLE
Sami freezes game in multiplayer

### ISSUE THREAD

**Issue by TheSmashBoy** [Project-M-CC/sami#1]
Title says it all. How is this fixed? It appears to be somehow random but it has gotten persistent. Some of my friends in my past tournament could not play Sami because of this. Before I restricted it to Battlefield and Final Destination but it now just happens in all stages. Again, it is occasional and only on multiplayer. Has this happened to anyone? Please help. I'm about to go to one of my friend's house to play PMCC with Sami in the roster and one like to play as Sami and can't because of this glitch.

**Comment by bb010g** [comment]
First thing: why the heck are you running Sami in tourney? She's nowhere near seriously usable.

Is this happening on the normal build or PMEX?

**Comment by TheSmashBoy** [comment]
@bb010g It's the current build. The original not PMEX.

**Comment by TheSmashBoy** [comment]
I will close this, the multiplayer issue is solved with PMEX.
